In [1]:
#Importing the tensorflow
import tensorflow as tf
tf.__version__

'2.6.4'

In [2]:
#Defining constants
x=tf.constant([2])
print(x)
y=tf.constant([[1,2,3,4],[1,2,3,8]])
print(y)

tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [1 2 3 8]], shape=(2, 4), dtype=int32)


2022-07-06 17:36:39.211193: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
g=tf.ones((2,2),dtype=tf.int32)
print(g)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [4]:
a=tf.zeros((9,9))
print(a)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(9, 9), dtype=float32)


In [5]:
x=tf.eye(4)
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [6]:
#Finding random matrix with mean=0, and std=1
x=tf.random.normal((4,4),mean=800,stddev=10)
print(x)

tf.Tensor(
[[794.5786  799.09784 799.4703  827.19257]
 [818.58435 803.37524 802.58167 804.56464]
 [779.3455  793.6819  802.8699  797.24384]
 [806.2651  780.1997  796.3649  799.68085]], shape=(4, 4), dtype=float32)


In [7]:
#Finding random matrix with minimum value=1 and max value=10
x=tf.random.uniform((2,3),minval=1,maxval=10)
print(x)

tf.Tensor(
[[2.6060243 5.1612453 3.253797 ]
 [1.0411451 8.003285  7.905019 ]], shape=(2, 3), dtype=float32)


In [8]:
x=tf.range(100)
print(x)

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99], shape=(100,), dtype=int32)


In [9]:
x=tf.range(start=10.2,limit=100.99,delta=2)
print(x)

tf.Tensor(
[ 10.2  12.2  14.2  16.2  18.2  20.2  22.2  24.2  26.2  28.2  30.2  32.2
  34.2  36.2  38.2  40.2  42.2  44.2  46.2  48.2  50.2  52.2  54.2  56.2
  58.2  60.2  62.2  64.2  66.2  68.2  70.2  72.2  74.2  76.2  78.2  80.2
  82.2  84.2  86.2  88.2  90.2  92.2  94.2  96.2  98.2 100.2], shape=(46,), dtype=float32)


In [10]:
#Changing the datatype of x from float to integer
x=tf.cast(x,dtype=tf.int64)
print(x)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int64)


In [11]:
x=tf.constant(2.8)
print(x)

tf.Tensor(2.8, shape=(), dtype=float32)


In [12]:
x=tf.cast(x,dtype=tf.int32)
print(x)

tf.Tensor(2, shape=(), dtype=int32)


In [13]:
#Mathematical operations
x=tf.constant([1,2,3])
y=tf.constant([4,5,6])
z=tf.add(x,y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [14]:
z=x+y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [15]:
z=tf.multiply(x,y)
print(z)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [16]:
#Dot product of x and y
z=tf.tensordot(x,y,axes=1)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [17]:
z=tf.reduce_sum(x*y,axis=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [18]:
z=x**2
print(z)

tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [19]:
x=tf.random.normal((2,2))
print(x)

tf.Tensor(
[[ 1.3175894   0.56527305]
 [-0.48597163 -0.01611688]], shape=(2, 2), dtype=float32)


In [20]:
c=tf.random.normal((3,6))
print(c)

tf.Tensor(
[[-1.186634   -0.7979198  -0.78520054 -0.62639064  1.7567343   0.5699243 ]
 [ 0.5248487  -0.6151739   0.16323252 -1.8050196  -0.21117309  0.7544309 ]
 [ 1.1911602  -0.21222854 -1.2059836   2.017528    0.64771664  1.7177929 ]], shape=(3, 6), dtype=float32)


In [21]:
x=tf.random.normal((3,3))
y=tf.random.normal((3,3))

In [22]:
#Multiply the matrices x and dy
z=tf.matmul(x,y)
print(z)

tf.Tensor(
[[-3.2393413   0.39313    -2.216203  ]
 [ 4.4347186   0.50039095  2.9679625 ]
 [ 3.6631188  -1.3066992   1.2378366 ]], shape=(3, 3), dtype=float32)


In [23]:
z=x @ y #Same as matrix multiplication
print(z)

tf.Tensor(
[[-3.2393413   0.39313    -2.216203  ]
 [ 4.4347186   0.50039095  2.9679625 ]
 [ 3.6631188  -1.3066992   1.2378366 ]], shape=(3, 3), dtype=float32)


In [24]:
#INDEXING
x=tf.constant([1,23,45,68,9])

In [25]:
print(x[:])

tf.Tensor([ 1 23 45 68  9], shape=(5,), dtype=int32)


In [26]:
print(x[1:4])

tf.Tensor([23 45 68], shape=(3,), dtype=int32)


In [27]:
print(x[::2])

tf.Tensor([ 1 45  9], shape=(3,), dtype=int32)


In [28]:
print(x[::-1])

tf.Tensor([ 9 68 45 23  1], shape=(5,), dtype=int32)


In [29]:
indices=tf.constant([4,1])
x_ind=tf.gather(x,indices)
print(x_ind)

tf.Tensor([ 9 23], shape=(2,), dtype=int32)


In [30]:
x=tf.constant([
[1,2,3],
[3,4,7],
[9,96,5]

])

In [31]:
print(x[:])

tf.Tensor(
[[ 1  2  3]
 [ 3  4  7]
 [ 9 96  5]], shape=(3, 3), dtype=int32)


In [32]:
print(x[0,:])

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [33]:
print(x[1:100,:])

tf.Tensor(
[[ 3  4  7]
 [ 9 96  5]], shape=(2, 3), dtype=int32)


In [34]:
x=tf.range(6)

In [35]:
print(x)

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)


In [36]:
#RESHAPING
x=tf.reshape(x,(2,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [37]:
#Finding the transpose matrix of x
x=tf.transpose(x,perm=[1,0])
print(x)

tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32)
