In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras import models,layers
from sklearn.model_selection import train_test_split
data=pd.read_csv('../input/sentiment140/training.1600000.processed.noemoticon.csv',encoding='latin1',header=None)
data.head()

0           1                             2         3                4  \
0  0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  _TheSpecialOne_   
1  0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY    scotthamilton   
2  0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY         mattycus   
3  0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY          ElleCTF   
4  0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY           Karoli   

                                                   5  
0  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1  is upset that he can't update his Facebook by ...  
2  @Kenichan I dived many times for the ball. Man...  
3    my whole body feels itchy and like its on fire   
4  @nationwideclass no, it's not behaving at all....

In [3]:
data=data.drop(columns=[1,2,3,4],axis=1)
data

0                                                  5
0        0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1        0  is upset that he can't update his Facebook by ...
2        0  @Kenichan I dived many times for the ball. Man...
3        0    my whole body feels itchy and like its on fire 
4        0  @nationwideclass no, it's not behaving at all....
...     ..                                                ...
1599995  4  Just woke up. Having no school is the best fee...
1599996  4  TheWDB.com - Very cool to hear old Walt interv...
1599997  4  Are you ready for your MoJo Makeover? Ask me f...
1599998  4  Happy 38th Birthday to my boo of alll time!!! ...
1599999  4  happy #charitytuesday @theNSPCC @SparksCharity...

[1600000 rows x 2 columns]

In [4]:
data.shape

(1600000, 2)

In [5]:
data.isnull().sum()

0    0
5    0
dtype: int64

In [6]:
data.columns=['sentiment','tweets']
data.head()

sentiment                                             tweets
0          0  @switchfoot http://twitpic.com/2y1zl - Awww, t...
1          0  is upset that he can't update his Facebook by ...
2          0  @Kenichan I dived many times for the ball. Man...
3          0    my whole body feels itchy and like its on fire 
4          0  @nationwideclass no, it's not behaving at all....

In [7]:
data['sentiment'].value_counts()

0    800000
4    800000
Name: sentiment, dtype: int64

In [8]:
data1=data[data['sentiment']==0].sample(2500)
data2=data[data['sentiment']==4].sample(2500)

In [9]:
df=data1.append(data2)

In [10]:
df.shape

(5000, 2)

In [11]:
text=df['tweets'].to_list()

In [12]:
text

['Finnish Minister Sirkka-Liisa Anttila wants another species dead on her watch: Saimaa Ringed Seal http://areena.yle.fi/video/172977 ',
 'Doesnt want to go back to school at all ',
 "@ricandhislife I've got to check my mail. ",
 'For a moment sahara and eastern looked like brand blvd. Whhhaaaaaaa  HOME!',
 'Now running iPhone OS 3.0  but sadly still on my iPhone 2G ',
 "It hurts to see my sister and her boyfriend.  And I don't know why.",
 "Lazy afternoon. My computer won't connect to the internet. ",
 'ssssssssssssooooooooooooooo bored.  just took a 3 hour nap.',
 'I miss the sound of his voice and how he makes me laugh ',
 "Want a holiday but there's not enough time!!! ",
 'My mom just fucked everything up  including my mood.',
 "@aglassjar Sorry  I still have to pay mine...I'm scared to check how much it will cost me.",
 'what a fuck is wrong with you fucking asshole  ...?',
 "@feliciaodg argh, sorry, he's just been a thorn in my side since we got him. rude, mouthy, etc. ",
 'I hat

In [13]:
token=Tokenizer()
token.fit_on_texts(text)

In [14]:
len(token.index_word)

11697

In [15]:
vocab_size=len(token.word_index)+1
vocab_size

11698

In [16]:
encoded_text=token.texts_to_sequences(text)
print(encoded_text)

[[3595, 3596, 3597, 3598, 3599, 530, 167, 3600, 848, 14, 121, 168, 3601, 3602, 3603, 33, 3604, 3605, 2272, 336, 3606], [1031, 63, 2, 37, 52, 2, 160, 24, 34], [3607, 164, 48, 2, 301, 6, 1397], [10, 4, 471, 3608, 5, 2273, 930, 40, 1032, 3609, 3610, 80], [27, 772, 267, 1033, 89, 488, 19, 709, 69, 14, 6, 267, 3611], [8, 449, 2, 82, 6, 585, 5, 121, 1034, 5, 1, 55, 57, 113], [773, 774, 6, 508, 316, 1398, 2, 3, 450], [3612, 214, 20, 586, 4, 89, 451, 587], [1, 92, 3, 658, 12, 235, 588, 5, 74, 108, 342, 13, 1187], [63, 4, 849, 19, 531, 23, 386, 50], [6, 400, 20, 1399, 387, 29, 1692, 6, 489], [3613, 123, 1, 69, 16, 2, 532, 490, 18, 589, 2, 301, 74, 93, 8, 61, 1693, 13], [58, 4, 590, 9, 354, 21, 7, 659, 3614], [3615, 931, 123, 452, 20, 105, 4, 3616, 11, 6, 556, 261, 67, 48, 149, 1400, 3617, 1401], [1, 157, 8, 2274, 60, 3618, 73, 51, 2275, 62, 317, 3619, 73, 3620, 1402, 62, 62, 62, 65, 3621, 3622, 3623], [92, 775, 31, 623, 26, 94, 203, 12, 6, 1403, 491, 184], [9, 533, 3624, 6, 710, 1694, 102, 83, 

In [17]:
max_length=200
x=sequence.pad_sequences(encoded_text,maxlen=max_length,padding='pre')
x

array([[    0,     0,     0, ...,  2272,   336,  3606],
       [    0,     0,     0, ...,   160,    24,    34],
       [    0,     0,     0, ...,   301,     6,  1397],
       ...,
       [    0,     0,     0, ...,   354,    44, 11693],
       [    0,     0,     0, ...,  1629,     5,  2477],
       [    0,     0,     0, ...,    24,     3, 11697]], dtype=int32)

In [18]:
x.shape

(5000, 200)

In [19]:
y=df['sentiment']
y.head()

590954    0
25899     0
528684    0
80511     0
667108    0
Name: sentiment, dtype: int64

In [20]:
y.value_counts()

0    2500
4    2500
Name: sentiment, dtype: int64

In [21]:
y=y.map({0:0,4:1})
y.shape

(5000,)

In [22]:
y.value_counts()

0    2500
1    2500
Name: sentiment, dtype: int64

In [23]:
vec_size=500
nn=models.Sequential([
    
    layers.Embedding(vocab_size,vec_size,input_length=max_length),
    layers.Conv1D(64,8,activation='relu'),
    layers.MaxPooling1D(2),
    layers.Dropout(0.8),
    
    layers.Dense(40,activation='relu'),
    layers.Dropout(0.9),
    
    layers.Dense(29,activation='relu'),
    layers.GlobalMaxPooling1D(),
    
    layers.Dense(1,activation='sigmoid')
    
    
    ])

2022-07-14 18:21:20.758119: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [24]:
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 200, 500)          5849000   
_________________________________________________________________
conv1d (Conv1D)              (None, 193, 64)           256064    
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 96, 64)            0         
_________________________________________________________________
dropout (Dropout)            (None, 96, 64)            0         
_________________________________________________________________
dense (Dense)                (None, 96, 40)            2600      
_________________________________________________________________
dropout_1 (Dropout)          (None, 96, 40)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 96, 29)            1

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
nn.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
nn.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=25)

Epoch 1/25


2022-07-14 18:21:21.069872: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


125/125 [==============================] - 24s 181ms/step - loss: 0.7149 - accuracy: 0.5132 - val_loss: 0.6917 - val_accuracy: 0.5420
Epoch 2/25
125/125 [==============================] - 23s 182ms/step - loss: 0.7017 - accuracy: 0.5190 - val_loss: 0.6934 - val_accuracy: 0.5000
Epoch 3/25
125/125 [==============================] - 27s 217ms/step - loss: 0.6841 - accuracy: 0.5663 - val_loss: 0.6873 - val_accuracy: 0.5260
Epoch 4/25
125/125 [==============================] - 22s 178ms/step - loss: 0.6573 - accuracy: 0.6185 - val_loss: 0.6803 - val_accuracy: 0.5710
Epoch 5/25
125/125 [==============================] - 22s 179ms/step - loss: 0.6050 - accuracy: 0.6790 - val_loss: 0.6720 - val_accuracy: 0.5910
Epoch 6/25
125/125 [==============================] - 21s 171ms/step - loss: 0.5123 - accuracy: 0.7545 - val_loss: 0.6555 - val_accuracy: 0.6150
Epoch 7/25
125/125 [==============================] - 22s 174ms/step - loss: 0.4141 - accuracy: 0.8300 - val_loss: 0.6359 - val_accuracy: 0.6

In [26]:
nn.evaluate(x_train,y_train)

125/125 [==============================] - 4s 31ms/step - loss: 0.1831 - accuracy: 0.9795


[0.18308374285697937, 0.9794999957084656]

In [27]:
nn.evaluate(x_test,y_test)

32/32 [==============================] - 1s 30ms/step - loss: 0.7078 - accuracy: 0.6440


[0.7078359723091125, 0.6439999938011169]

In [28]:
x_test

array([[   0,    0,    0, ...,   36,   15, 2269],
       [   0,    0,    0, ...,   59,   51, 1644],
       [   0,    0,    0, ...,   12,    8,   42],
       ...,
       [   0,    0,    0, ..., 8836,   12, 1924],
       [   0,    0,    0, ...,    0,    0,  784],
       [   0,    0,    0, ...,   43,  851, 5059]], dtype=int32)

In [29]:
x_test=np.array(x_test)
x_test

array([[   0,    0,    0, ...,   36,   15, 2269],
       [   0,    0,    0, ...,   59,   51, 1644],
       [   0,    0,    0, ...,   12,    8,   42],
       ...,
       [   0,    0,    0, ..., 8836,   12, 1924],
       [   0,    0,    0, ...,    0,    0,  784],
       [   0,    0,    0, ...,   43,  851, 5059]], dtype=int32)

In [30]:
y_train

819284     1
405417     0
147882     0
964976     1
339979     0
          ..
1022471    1
1214849    1
394311     0
1002408    1
60144      0
Name: sentiment, Length: 4000, dtype: int64

In [31]:
preds=nn.predict(x_test)
preds=(preds>0.5)
preds[:5]

array([[False],
       [ True],
       [ True],
       [False],
       [ True]])

# Custom prediction a sentence

In [32]:
def get_encoded(x):
    x=token.texts_to_sequences(x)
    x=sequence.pad_sequences(x,maxlen=max_length,padding='pre')
    return x

In [33]:
h=['He is good']

In [34]:
h=get_encoded(h)
h

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [35]:
nn.predict(h)

array([[0.6247622]], dtype=float32)

In [36]:
nn2=models.Sequential([
    
    layers.Embedding(vocab_size,vec_size,input_length=max_length),
    layers.Dropout(0.5),
    layers.Bidirectional(layers.LSTM(199)),
    layers.Dropout(0.4),
    layers.Dense(399,activation='relu'),
    layers.Dropout(0.7),
    layers.Dense(43,activation='relu'),
    layers.Dropout(0.8),
    layers.Dense(1,activation='sigmoid')
    
])
    
    

In [39]:
nn2.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
nn2.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=2,batch_size=1000)

Epoch 1/2
4/4 [==============================] - 80s 19s/step - loss: 0.0108 - accuracy: 0.9940 - val_loss: 3.9934 - val_accuracy: 0.6780
Epoch 2/2
4/4 [==============================] - 71s 19s/step - loss: 0.0119 - accuracy: 0.9952 - val_loss: 4.3168 - val_accuracy: 0.6750
