In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[ 'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I want to be a tensorflow developer',
     'understand the meaning of words',
     'your videos are amazing']

In [5]:
print(sent)

['the glass of milk', 'the glass of juice', 'the cup of tea', 'I am a good boy', 'I want to be a tensorflow developer', 'understand the meaning of words', 'your videos are amazing']


In [6]:
voc_size=10000
one_hot_rep=[one_hot(words,voc_size) for words in sent]
one_hot_rep

[[3687, 6973, 7319, 4581],
 [3687, 6973, 7319, 5917],
 [3687, 9375, 7319, 7325],
 [3849, 3891, 3213, 6777, 5770],
 [3849, 8233, 8950, 2394, 3213, 2551, 5306],
 [2985, 3687, 2414, 7319, 407],
 [614, 1270, 6557, 4923]]

In [11]:
from tensorflow.keras import models,layers
from tensorflow.keras.preprocessing import sequence
import numpy as np

In [9]:
sent_length=10
embedded_docs=sequence.pad_sequences(one_hot_rep,padding='post',maxlen=sent_length)
embedded_docs

array([[3687, 6973, 7319, 4581,    0,    0,    0,    0,    0,    0],
       [3687, 6973, 7319, 5917,    0,    0,    0,    0,    0,    0],
       [3687, 9375, 7319, 7325,    0,    0,    0,    0,    0,    0],
       [3849, 3891, 3213, 6777, 5770,    0,    0,    0,    0,    0],
       [3849, 8233, 8950, 2394, 3213, 2551, 5306,    0,    0,    0],
       [2985, 3687, 2414, 7319,  407,    0,    0,    0,    0,    0],
       [ 614, 1270, 6557, 4923,    0,    0,    0,    0,    0,    0]],
      dtype=int32)

In [12]:
dim=9
nn=models.Sequential([
    
    layers.Embedding(voc_size,9,input_length=sent_length)
    
    
])

2022-07-07 05:43:37.987500: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [13]:
nn.compile(optimizer='adam',loss='binary_crossentropy',metrics='accuracy')

In [14]:
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 9)             90000     
Total params: 90,000
Trainable params: 90,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
nn.predict(embedded_docs)

2022-07-07 05:46:15.720026: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


array([[[ 8.4985867e-03, -2.9812658e-02, -2.6784290e-02,  5.7571046e-03,
         -6.6657551e-03,  6.2443726e-03, -3.0926287e-02,  1.4406253e-02,
         -1.2919009e-02],
        [ 3.5952244e-02,  3.0782986e-02,  1.1906251e-03, -1.0251295e-02,
          1.9163106e-02,  3.0439023e-02,  4.1063372e-02,  1.3436787e-03,
         -4.9276460e-02],
        [ 2.3543093e-02,  3.6264110e-02, -1.9022450e-03, -1.7292190e-02,
         -4.3148994e-02,  4.4398915e-02,  4.0645707e-02, -2.4821615e-02,
         -3.3292890e-02],
        [ 4.2448346e-02,  2.8777670e-02, -1.9643418e-03, -3.4696460e-03,
          2.2156779e-02, -6.7785382e-03, -7.9343319e-03,  3.0287217e-02,
         -2.3350108e-02],
        [ 4.8471499e-02,  2.7454410e-02, -2.2177769e-02,  3.1982649e-02,
          1.3476405e-02,  4.0630922e-03, -3.7356902e-02, -1.0635771e-02,
          1.8617723e-02],
        [ 4.8471499e-02,  2.7454410e-02, -2.2177769e-02,  3.1982649e-02,
          1.3476405e-02,  4.0630922e-03, -3.7356902e-02, -1.0635771

In [16]:
embedded_docs[0]

array([3687, 6973, 7319, 4581,    0,    0,    0,    0,    0,    0],
      dtype=int32)

In [20]:
nn.predict(embedded_docs)[0]

array([[ 0.00849859, -0.02981266, -0.02678429,  0.0057571 , -0.00666576,
         0.00624437, -0.03092629,  0.01440625, -0.01291901],
       [ 0.03595224,  0.03078299,  0.00119063, -0.01025129,  0.01916311,
         0.03043902,  0.04106337,  0.00134368, -0.04927646],
       [ 0.02354309,  0.03626411, -0.00190224, -0.01729219, -0.04314899,
         0.04439892,  0.04064571, -0.02482161, -0.03329289],
       [ 0.04244835,  0.02877767, -0.00196434, -0.00346965,  0.02215678,
        -0.00677854, -0.00793433,  0.03028722, -0.02335011],
       [ 0.0484715 ,  0.02745441, -0.02217777,  0.03198265,  0.01347641,
         0.00406309, -0.0373569 , -0.01063577,  0.01861772],
       [ 0.0484715 ,  0.02745441, -0.02217777,  0.03198265,  0.01347641,
         0.00406309, -0.0373569 , -0.01063577,  0.01861772],
       [ 0.0484715 ,  0.02745441, -0.02217777,  0.03198265,  0.01347641,
         0.00406309, -0.0373569 , -0.01063577,  0.01861772],
       [ 0.0484715 ,  0.02745441, -0.02217777,  0.03198265,  0